/**
 * Pre-compiles LWC icon SVG HTML templates into bundled JS modules.
 *
 * Instead of Vite serving 1,614 individual .html files through its transform
 * pipeline at runtime (which is extremely slow in cloud environments), this
 * script compiles them ahead of time into 4 single JS files — one per icon set.
 *
 * Usage: node scripts/prebuild-icons.mjs
 */
import { compile } from '@lwc/template-compiler';
import fs from 'fs';
import path from 'path';

const ICON_SETS = [
    {
        name: 'utility',
        dir: 'node_modules/lightning-base-components/src/lightning/iconSvgTemplatesUtility/buildTemplates/utility',
        output: 'src/build/generated/iconSvgUtility.js',
    },
    {
        name: 'standard',
        dir: 'node_modules/lightning-base-components/src/lightning/iconSvgTemplatesStandard/buildTemplates/standard',
        output: 'src/build/generated/iconSvgStandard.js',
    },
    {
        name: 'doctype',
        dir: 'node_modules/lightning-base-components/src/lightning/iconSvgTemplatesDoctype/buildTemplates/doctype',
        output: 'src/build/generated/iconSvgDoctype.js',
    },
    {
        name: 'action',
        dir: 'node_modules/lightning-base-components/src/lightning/iconSvgTemplatesAction/buildTemplates/action',
        output: 'src/build/generated/iconSvgAction.js',
    },
];

// Ensure output directory exists
const outDir = 'src/build/generated';
if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
}

for (const iconSet of ICON_SETS) {
    const htmlFiles = fs.readdirSync(iconSet.dir)
        .filter(f => f.endsWith('.html'))
        .sort();

    let output = `// Auto-generated by scripts/prebuild-icons.mjs — do not edit\n`;
    output += `import { freezeTemplate, parseFragment, registerTemplate, sanitizeAttribute } from 'lwc';\n\n`;

    const exportEntries = [];

    for (let i = 0; i < htmlFiles.length; i++) {
        const file = htmlFiles[i];
        const filePath = path.join(iconSet.dir, file);
        const html = fs.readFileSync(filePath, 'utf8');
        const baseName = path.basename(file, '.html');
        const exportName = `${iconSet.name}_${baseName}`;

        const result = compile(html, filePath, {});

        if (result.warnings && result.warnings.length > 0) {
            console.warn(`  Warning compiling ${file}:`, result.warnings.map(w => w.message));
        }

        let code = result.code;

        // Strip implicit CSS imports (the icon templates don't have CSS)
        code = code.replace(/import _implicitStylesheets from [^\n]+\n/g, '');
        code = code.replace(/import _implicitScopedStylesheets from [^\n]+\n/g, '');

        // Strip lwc import (we have a single one at the top)
        code = code.replace(/import \{[^}]+\} from ["']lwc["'];?\n/g, '');

        // Strip the CSS-related code at the bottom
        code = code.replace(/tmpl\.stylesheets = \[\];[\s\S]*?freezeTemplate\(tmpl\);/,
            'freezeTemplate(tmpl);');
        // Also strip any remaining _implicitStylesheets references
        code = code.replace(/if \(_implicitStylesheets\) \{[\s\S]*?\}\n/g, '');
        code = code.replace(/if \(_implicitScopedStylesheets\) \{[\s\S]*?\}\n/g, '');

        // Rename 'tmpl' function and all references to a unique name
        const uniqueName = `tmpl_${i}`;
        // Replace function declaration
        code = code.replace(/function tmpl\(/, `function ${uniqueName}(`);
        // Replace export default registerTemplate(tmpl)
        code = code.replace(/export default registerTemplate\(tmpl\)/, `const ${exportName} = registerTemplate(${uniqueName})`);
        // Replace tmpl.stylesheetToken etc
        code = code.replace(/tmpl\.stylesheetToken/g, `${uniqueName}.stylesheetToken`);
        code = code.replace(/tmpl\.legacyStylesheetToken/g, `${uniqueName}.legacyStylesheetToken`);
        code = code.replace(/tmpl\.stylesheets/g, `${uniqueName}.stylesheets`);
        code = code.replace(/freezeTemplate\(tmpl\)/, `freezeTemplate(${uniqueName})`);

        // Rename $fragment variables to avoid conflicts
        code = code.replace(/\$fragment(\d+)/g, `$fragment_${i}_$1`);

        output += `// ${file}\n`;
        output += code.trim() + '\n\n';
        exportEntries.push(exportName);
    }

    // Build the default export object
    output += `export default {\n`;
    for (const name of exportEntries) {
        output += `    ${name},\n`;
    }
    output += `};\n`;

    fs.writeFileSync(iconSet.output, output);
    console.log(`✓ ${iconSet.name}: ${htmlFiles.length} icons → ${iconSet.output}`);
}

// Clean up test script if it exists
if (fs.existsSync('scripts/test-compile.mjs')) {
    fs.unlinkSync('scripts/test-compile.mjs');
}

console.log('\nDone! Pre-compiled icon templates are ready.');
